spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: dev
  datasource:
    url: ${DEV_MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DEV_MYSQL_USER}
    password: ${DEV_MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    org:
      springframework:
        web: DEBUG

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  issuer: ${JWT_ISSUER}
  salt: ${JWT_SALT}
  access-token:
    expiretime: ${DEV_JWT_ACCESS_TOKEN_EXPIRETIME}
  refresh-token:
    expiretime: ${DEV_JWT_REFRESH_TOKEN_EXPIRETIME}
