spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: dev

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password

  datasource:
    url: ${DEV_MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DEV_MYSQL_USER}
    password: ${DEV_MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  data:
    redis:
      host: redis
      port: 6379

    mongodb:
      uri: ${DEV_MONGODB_URI}
      database: ${DEV_MONGODB_DATABASE}
      authentication-database: admin
      auto-index-creation: true

logging:
  level:
    org:
      springframework:
        web: DEBUG

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  issuer: ${JWT_ISSUER}
  salt: ${JWT_SALT}
  access:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

## fast API 주소
fast:
  api:
    base-url: ${FAST_API_BASE_URL}
    stress-endpoint: ${STRESS_ENDPOINT}

## FCM 서비스 JSON 위치
fcm:
  key: ${FCM_SERVICE_ACCOUNT_KEY}