spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${LOCAL_MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_MYSQL_USER}
    password: ${LOCAL_MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

    mongodb:
      uri: ${LOCAL_MONGODB_URI}
      database: ${LOCAL_MONGODB_DATABASE}
      authentication-database: admin
      auto-index-creation: true

logging:
  level:
    org:
      springframework:
        web: DEBUG

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  issuer: ${JWT_ISSUER}
  salt: ${JWT_SALT}
  access:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

springdoc:
  swagger-ui:
    path: ${SWAGGER_UI_PATH}  # Swagger UI에 접근할 URL 경로
  api-docs:
    path: ${SWAGGER_API_DOCS_PATH}

## fast API 주소
fast:
  api:
    base-url: ${FAST_API_BASE_URL}
    stress-endpoint: ${STRESS_ENDPOINT}

## FCM 서비스 JSON 위치
fcm:
  key: ${FCM_SERVICE_ACCOUNT_KEY}